[project]
name = "data-engineering-zoomcamp-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "dbt-duckdb>=1.9.0",
    "duckdb",
]
            